---
- name: qBittorrent | Check configuration
  become: true
  slurp:
    src: "{{ homeflix_host_volume }}/qbittorrent/qBittorrent/qBittorrent.conf"
  register: conf_file

- name: qBittorrent | Determine first run
  set_fact:
    qbittorrent_first_run: "{{ 'Password_PBKDF2' not in (conf_file.content | b64decode) }}"

- name: block - First run tasks
  when: qbittorrent_first_run
  block:
    - name: qBittorrent | Include task to stop the service
      vars:
        service_name: qbittorrent
      include_tasks: stop_service.yml

    - name: qBittorrent | Copy config file
      copy:
        src: qBittorrent.conf
        dest: "{{ homeflix_host_volume }}/qbittorrent/qBittorrent/qBittorrent.conf"
        owner: "{{ homeflix_puid }}"
        group: "{{ homeflix_pgid }}"
        mode: "0664"
      notify: restart qbittorrent
