---
- name: Recyclarr | Check Radarr configuration
  slurp:
    src: "{{ homeflix_host_dir }}/radarr/config.xml"
  register: radarr_xml

- name: Recyclarr | Check Sonarr configuration
  slurp:
    src: "{{ homeflix_host_dir }}/sonarr/config.xml"
  register: sonarr_xml

- name: Recyclarr | Generate settings file
  vars:
    radarr_api_key: "{{ ((radarr_xml.content | b64decode) | regex_findall('<ApiKey>(.*?)</ApiKey>'))[0] }}"
    sonarr_api_key: "{{ ((sonarr_xml.content | b64decode) | regex_findall('<ApiKey>(.*?)</ApiKey>'))[0] }}"
  template:
    src: recyclarr.yml.j2
    dest: "{{ homeflix_host_dir }}/recyclarr/recyclarr.yml"
    owner: "{{ homeflix_puid }}"
    group: "{{ homeflix_pgid }}"
    mode: "0644"
  notify: restart recyclarr

- name: Recyclarr | Please read this message
  debug:
    msg: "The 'Sync quality profiles' task will take a while on first run. Please be patient."

- name: Recyclarr | Sync quality profiles
  become: true
  community.docker.docker_container_exec:
    container: recyclarr
    user: 0 # root
    command: recyclarr sync
    env:
      GIT_HTTP_VERSION: HTTP/1.1
