---
- name: Restart Jellyfin and wait until is up
  block:
    - name: Restart Jellyfin
      vars:
        service_name: jellyfin
      include_tasks: restart_service.yml
      listen: restart jellyfin

    - name: Wait until Jellyfin is loaded
      uri:
        url: "http://localhost:{{ homeflix_jellyfin_port }}/Startup/Configuration"
        method: GET
        headers:
          X-Emby-Token: "{{ homeflix_jellyfin_api_key }}"
      register: jellyfin_up
      until: jellyfin_up.status == 200
      retries: 30
      delay: 5
      listen: restart jellyfin

- name: Restart qBittorrent
  vars:
    service_name: qbittorrent
  include_tasks: restart_service.yml
  listen: restart qbittorrent

- name: Restart Recyclarr
  vars:
    service_name: recyclarr
  include_tasks: restart_service.yml
  listen: restart recyclarr
