---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: homeflix-molecule
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible
    privileged: true
    pre_build_image: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      all:
        molecule_test: true

verifier:
  name: ansible
